<a href="https://colab.research.google.com/github/phlapapon-kulto/PythonDataViz2026/blob/main/Hw6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### HW6

### 1. คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
### 2. คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น
### 3. หาจำนวนผู้ป่วยที่เป็นคน "คนต่างชาติเดินทางมาจากต่างประเทศ

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
path = '/content/drive/My Drive/PythonDataViz2026'
file_path = os.path.join(path,'confirmed-cases.csv')
print(file_path)

/content/drive/My Drive/PythonDataViz2026/confirmed-cases.csv

In [ ]:
data_covid = pd.read_csv(file_path)
data_covid.head()

/tmp/ipykernel_1606/908241447.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [ ]:
data_covid.shape

(839771, 11)

In [ ]:
data = data_covid[['sex','age','province_of_onset']]
data

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[839771 rows x 3 columns]

In [ ]:
female_data = data[data['sex'] == 'หญิง']
female_numeric_age = pd.to_numeric(female_data['age'], errors='coerce')
print(female_numeric_age.head())

0    61.0
1    74.0
2    73.0
4    66.0
5    33.0
Name: age, dtype: float64

In [ ]:
sum = 0
N = 0
for a in female_numeric_age:
    if a > 0:
        sum += a
        N += 1
print(f'อายุเฉลี่ยของผู้ป่วยหญิง:{sum/N}')

อายุเฉลี่ยของผู้ป่วยหญิง:36.16090881617699

In [ ]:
female_kk = female_data[female_data['province_of_onset'] == 'ขอนแก่น']
female_kk_numeric = pd.to_numeric(female_kk['age'], errors='coerce')
print(female_kk_numeric.head())

463     36.0
1971    70.0
2638    63.0
5949    32.0
6083    36.0
Name: age, dtype: float64

In [ ]:
sum = 0
N = 0
for a in female_kk_numeric :
    if a > 0:
        sum += a
        N += 1

print(f'อายุเฉลี่ยของผู้ป่วยหญิงในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ยของผู้ป่วยหญิงในจังหวัดขอนแก่น 34.59362745098039

In [ ]:
male_data = data[data['sex'] == 'ชาย']
male_numeric_age = pd.to_numeric(male_data['age'], errors='coerce')
print(male_numeric_age.head())

3     68.0
8     63.0
10    33.0
11    61.0
12     6.0
Name: age, dtype: float64

In [ ]:
sum = 0
N = 0
for a in male_numeric_age:
    if a > 0:
        sum += a
        N += 1
print(f'อายุเฉลี่ยของผู้ป่วยชาย:{sum/N}')

อายุเฉลี่ยของผู้ป่วยชาย:34.962927021309376

In [ ]:
male_kk = male_data[male_data['province_of_onset'] == 'ขอนแก่น']
male_kk_numeric = pd.to_numeric(male_kk['age'], errors='coerce')
print(male_kk_numeric.head())

181     33.0
1467    19.0
2674    68.0
9334    17.0
9335    20.0
Name: age, dtype: float64

In [ ]:
sum = 0
N = 0
for a in male_kk_numeric :
    if a > 0:
        sum += a
        N += 1

print(f'อายุเฉลี่ยของผู้ป่วยชายในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ยของผู้ป่วยชายในจังหวัดขอนแก่น 34.057632398753896

In [ ]:
foreign_travelers_count = data_covid[data_covid['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ'].shape[0]
print(f"จำนวนผู้ป่วยที่เป็นคนต่างชาติเดินทางมาจากต่างประเทศ : {foreign_travelers_count} คน")

จำนวนผู้ป่วยที่เป็นคนต่างชาติเดินทางมาจากต่างประเทศ: 225 คน