<a href="https://colab.research.google.com/github/phlapapon-kulto/PythonDataViz2026/blob/main/Hw7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW7 สร้างตารางใหม่ ที่ค่าใน sex เป็น missing ทั้งหมด
### - สรุปว่าทำไม record นั้นๆถึงเป็น missing

In [20]:
import pandas as pd
import os

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
path = '/content/drive/MyDrive'

In [23]:
file_path = os.path.join(path,'confirmed-cases.csv')

In [24]:
df = pd.read_csv(file_path)
df.head()

/tmp/ipykernel_1950/2641854224.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [32]:
df_missing_sex = df[df['sex'].isna()]
df_missing_sex

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
4397,4398,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4398,4399,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4399,4400,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4400,4401,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4401,4402,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
...,...,...,...,...,...,...,...,...,...,...,...
838332,838333,12/8/2021,11/8/2021,NaN,3.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางคอแหลม
839174,839175,12/8/2021,11/8/2021,NaN,47.0,ปี,Thailand,กรุงเทพมหานคร,ระบุไม่ได้,กรุงเทพมหานคร,บางคอแหลม
839304,839305,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
839396,839397,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN
839397,839398,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN

### ทำไม record ถึงเป็น missing
**สิทธิความเป็นส่วนตัว**: ผู้ให้ข้อมูลปฏิเสธการระบุเพศเนื่องจากเหตุผลด้านสิทธิส่วนบุคคล

**ข้อจำกัดของตัวเลือก**: โครงสร้างระบบรองรับเฉพาะเพศทางชีวภาพ (ชาย/หญิง) ทำให้ผู้มีความหลากหลายทางเพศไม่สามารถเลือกได้

**การปรับปรุงระบบภายหลัง**: ช่องข้อมูลเพศถูกเพิ่มเข้ามาภายหลัง ส่งผลให้สมาชิกเก่าไม่มีข้อมูลส่วนนี้

**ความผิดพลาดในการแปลงข้อมูล**: เกิดข้อผิดพลาดระหว่างย้ายฐานข้อมูล เช่น ระบบไม่รองรับตัวอักษรย่อยศหรือคำนำหน้า

**ความไม่สมบูรณ์ของเอกสารต้นทาง**: เอกสารลายลักษณ์อักษรชำรุด หรือลายมือไม่ชัดเจนจนไม่สามารถป้อนข้อมูลได้